name: WakaTime

on:
  workflow_dispatch: # for manual workflow trigger
#   schedule:
#     - cron: '0 0 * * *' # runs at every 12AM UTC

uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.wakatime.svg
  token: NOT_NEEDED
  base: ""
  plugin_wakatime: yes
  plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
  plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
